on:
  workflow_dispatch:

jobs:
  export_macos:
    runs-on: macos-14
    permissions: write-all
    name: Export macOS
    env:
      SOURCE_PATH: ${{ github.workspace }}/DeltaruneChinesePatcher
      GODOT_SOURCE_PATH: ${{ github.workspace }}/godot
      GODOT_EDITOR_PATH: ${{ github.workspace }}/godot/bin/godot.macos.editor.arm64.mono
      LOCAL_NUGET_PATH: ${{ github.workspace }}/local-nuget
      DOTNET_DOWNLOAD_PATH: ${{ github.workspace }}/dotnet-download

    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
      with:
        path: ${{ env.SOURCE_PATH }}

    - name: Setup .NET Download DIR & Change XCode Version
      run: |
        mkdir ${{ env.DOTNET_DOWNLOAD_PATH }}
        sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

    - name: Setup .NET 8
      working-directory: ${{ env.DOTNET_DOWNLOAD_PATH }}
      run: |
        wget https://dot.net/v1/dotnet-install.sh
        chmod +x dotnet-install.sh
        ./dotnet-install.sh
        echo "~/.dotnet" >> $GITHUB_PATH
        echo "DOTNET_ROOT=\"~/.dotnet\"" >> $GITHUB_ENV

    - name: Cache Godot Build Artifacts
      id: godot-cache
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.GODOT_SOURCE_PATH }}/bin
          ${{ env.GODOT_SOURCE_PATH }}/modules/mono/glue
          ${{ env.LOCAL_NUGET_PATH }}
        key: godot-build-${{ runner.os }}-4.4-${{ steps.godot_commit.outputs.hash }}
        restore-keys: |
          godot-build-${{ runner.os }}-4.4-

    - name: Clone Godot Engine
      if: steps.godot-cache.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: godotengine/godot
        path: ${{ env.GODOT_SOURCE_PATH }}
        ref: '4.4'
          
    - name: Install Godot Build Dependencies
      if: steps.godot-cache.outputs.cache-hit != 'true'
      run: |
        brew install scons
        chmod +x ${{ env.GODOT_SOURCE_PATH }}/misc/scripts/install_vulkan_sdk_macos.sh
        bash ${{ env.GODOT_SOURCE_PATH }}/misc/scripts/install_vulkan_sdk_macos.sh

    - name: Build Godot
      if: steps.godot-cache.outputs.cache-hit != 'true'
      working-directory: ${{ env.GODOT_SOURCE_PATH }}
      run: |
        scons platform=macos arch=arm64 target=editor module_mono_enabled=yes module_astcenc_enabled=no production=yes debug_symbols=no optimize=size module_text_server_adv_enabled=no module_text_server_fb_enabled=yes module_godot_physics_2d_enabled=no module_godot_physics_3d_enabled=no module_jolt_enabled=no disable_physics_2d=yes disable_physics_3d=yes module_basis_universal_enabled=no module_bcdec_enabled=no module_bmp_enabled=no module_camera_enabled=no module_csg_enabled=no module_dds_enabled=no module_enet_enabled=no module_etcpak_enabled=no module_fbx_enabled=no module_gltf_enabled=no module_gridmap_enabled=no module_hdr_enabled=no module_interactive_music_enabled=no module_jsonrpc_enabled=no module_ktx_enabled=no module_mbedtls_enabled=no module_meshoptimizer_enabled=no module_minimp3_enabled=no module_mobile_vr_enabled=no module_msdfgen_enabled=no module_multiplayer_enabled=no module_noise_enabled=no module_navigation_2d_enabled=no module_navigation_3d_enabled=no module_ogg_enabled=no module_openxr_enabled=no module_raycast_enabled=no module_regex_enabled=no module_svg_enabled=no module_tga_enabled=no module_theora_enabled=no module_tinyexr_enabled=no module_upnp_enabled=no module_vhacd_enabled=no module_vorbis_enabled=no module_webrtc_enabled=no module_websocket_enabled=no module_webxr_enabled=no module_zip_enabled=no
        scons platform=macos target=template_release arch=arm64 module_mono_enabled=yes disable_3d=yes module_astcenc_enabled=no production=yes debug_symbols=no optimize=size module_text_server_adv_enabled=no module_text_server_fb_enabled=yes module_godot_physics_2d_enabled=no module_godot_physics_3d_enabled=no module_jolt_enabled=no disable_physics_2d=yes disable_physics_3d=yes module_basis_universal_enabled=no module_bcdec_enabled=no module_bmp_enabled=no module_camera_enabled=no module_csg_enabled=no module_dds_enabled=no module_enet_enabled=no module_etcpak_enabled=no module_fbx_enabled=no module_gltf_enabled=no module_gridmap_enabled=no module_hdr_enabled=no module_interactive_music_enabled=no module_jsonrpc_enabled=no module_ktx_enabled=no module_mbedtls_enabled=no module_meshoptimizer_enabled=no module_minimp3_enabled=no module_mobile_vr_enabled=no module_msdfgen_enabled=no module_multiplayer_enabled=no module_noise_enabled=no module_navigation_2d_enabled=no module_navigation_3d_enabled=no module_ogg_enabled=no module_openxr_enabled=no module_raycast_enabled=no module_regex_enabled=no module_svg_enabled=no module_tga_enabled=no module_theora_enabled=no module_tinyexr_enabled=no module_upnp_enabled=no module_vhacd_enabled=no module_vorbis_enabled=no module_webrtc_enabled=no module_websocket_enabled=no module_webxr_enabled=no module_zip_enabled=no
        scons platform=macos target=template_release arch=x86_64 generate_bundle=yes module_mono_enabled=yes disable_3d=yes module_astcenc_enabled=no production=yes debug_symbols=no optimize=size module_text_server_adv_enabled=no module_text_server_fb_enabled=yes module_godot_physics_2d_enabled=no module_godot_physics_3d_enabled=no module_jolt_enabled=no disable_physics_2d=yes disable_physics_3d=yes module_basis_universal_enabled=no module_bcdec_enabled=no module_bmp_enabled=no module_camera_enabled=no module_csg_enabled=no module_dds_enabled=no module_enet_enabled=no module_etcpak_enabled=no module_fbx_enabled=no module_gltf_enabled=no module_gridmap_enabled=no module_hdr_enabled=no module_interactive_music_enabled=no module_jsonrpc_enabled=no module_ktx_enabled=no module_mbedtls_enabled=no module_meshoptimizer_enabled=no module_minimp3_enabled=no module_mobile_vr_enabled=no module_msdfgen_enabled=no module_multiplayer_enabled=no module_noise_enabled=no module_navigation_2d_enabled=no module_navigation_3d_enabled=no module_ogg_enabled=no module_openxr_enabled=no module_raycast_enabled=no module_regex_enabled=no module_svg_enabled=no module_tga_enabled=no module_theora_enabled=no module_tinyexr_enabled=no module_upnp_enabled=no module_vhacd_enabled=no module_vorbis_enabled=no module_webrtc_enabled=no module_websocket_enabled=no module_webxr_enabled=no module_zip_enabled=no

    - name: Generate Mono Glue & Build Assemblies
      if: steps.godot-cache.outputs.cache-hit != 'true'
      working-directory: ${{ env.GODOT_SOURCE_PATH }}
      run: |
        mkdir -p ${{ env.LOCAL_NUGET_PATH }}
        ${{ env.GODOT_EDITOR_PATH }} --headless --generate-mono-glue modules/mono/glue
        python3 ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --push-nupkgs-local ${{ env.LOCAL_NUGET_PATH }}
        
    - name: Configure Local NuGet Source
      run: |
        mkdir -p ${{ env.LOCAL_NUGET_PATH }}
        cat > nuget.config << EOL
        <?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <packageSources>
            <clear />
            <add key="local-godot" value="${{ env.LOCAL_NUGET_PATH }}" />
            <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
          </packageSources>
          <packageSourceMapping>
            <packageSource key="local-godot">
              <package pattern="Godot.NET.Sdk" />
              <package pattern="Godot.SourceGenerators" />
              <package pattern="GodotSharp" />
              <package pattern="GodotSharpEditor" />
            </packageSource>
            <packageSource key="nuget.org">
              <package pattern="*" />
            </packageSource>
          </packageSourceMapping>
        </configuration>
        EOL

    - name: .NET Restore
      run: dotnet restore
      working-directory: ${{ env.SOURCE_PATH }}

    - name: Build Solution
      run: dotnet build
      working-directory: ${{ env.SOURCE_PATH }}
      
    - name: Install Custom Export Template
      run: |
        TEMPLATE_DIR="/Users/runner/Library/Application Support/Godot/export_templates/4.4.2.rc.mono"
        mkdir -p "$TEMPLATE_DIR"
        cp ${{ env.GODOT_SOURCE_PATH }}/bin/godot_macos_mono.zip "${TEMPLATE_DIR}/macos.zip"

    - name: Export Project
      run: |
        mkdir -p ${{ github.workspace }}/build/DeltaruneChinesePatcher_macOS
        ${{ env.GODOT_EDITOR_PATH }} --headless --path ${{ env.SOURCE_PATH }} --export-release "macOS" "${{ github.workspace }}/build/DeltaruneChinesePatcher_macOS/DELTARUNE Chinese Patcher.app"

    - name: Strip
      run: |
        strip "${{ github.workspace }}/build/DeltaruneChinesePatcher_macOS/DELTARUNE Chinese Patcher.app/Contents/MacOS/DELTARUNE Chinese Patcher"

    - name: Archive and Upload Artifact (macOS)
      run: |
        cd ${{ github.workspace }}/build/DeltaruneChinesePatcher_macOS
        zip -r ../DeltaruneChinesePatcher_macOS.zip .
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: macOS
        path: ${{ github.workspace }}/build/DeltaruneChinesePatcher_macOS.zip