on:
  workflow_dispatch:

jobs:
  export_windows:
    runs-on: windows-latest
    permissions: write-all
    name: Export Windows
    env:
      SOURCE_PATH: ${{ github.workspace }}\DeltaruneChinesePatcher
      GODOT_SOURCE_PATH: ${{ github.workspace }}\godot\latest
      GODOT_EDITOR_PATH: ${{ github.workspace }}\godot\latest\bin\godot.windows.editor.x86_64.mono.exe
      GODOT_44_SOURCE_PATH: ${{ github.workspace }}\godot\4.4
      GODOT_44_EDITOR_PATH: ${{ github.workspace }}\godot\4.4\bin\godot.windows.editor.x86_64.mono.exe
      LOCAL_NUGET_PATH: ${{ github.workspace }}\local-nuget
      ANGLE_LIB_PATH: ${{ github.workspace }}\angle-lib

    steps:
    - name: Checkout Project
      uses: actions/checkout@v7
      with:
        path: ${{ env.SOURCE_PATH }}

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          8.0.x

    - name: Download UPX
      run: |
        mkdir ${{ github.workspace }}\upx
        curl -L -o ${{ github.workspace }}\upx\upx-5.2.0-win64.zip https://github.com/upx/upx/releases/download/v5.2.0/upx-5.2.0-win64.zip
        cd ${{ github.workspace }}\upx
        unzip upx-5.2.0-win64.zip

    - name: Cache Godot Build Artifacts
      id: godot-cache
      uses: actions/cache@v5
      with:
        path: |
          ${{ env.GODOT_SOURCE_PATH }}\bin
          ${{ env.GODOT_SOURCE_PATH }}\modules\mono\glue
          ${{ env.LOCAL_NUGET_PATH }}
        key: godot-build-${{ runner.os }}-4.7-${{ steps.godot_commit.outputs.hash }}
        restore-keys: |
          godot-build-${{ runner.os }}-4.7-

    - name: Cache Godot 4.4 Build Artifacts
      id: godot-cache-44
      uses: actions/cache@v5
      with:
        path: |
          ${{ env.GODOT_44_SOURCE_PATH }}\bin
          ${{ env.GODOT_44_SOURCE_PATH }}\modules\mono\glue
          ${{ env.LOCAL_NUGET_PATH }}
        key: godot-build-${{ runner.os }}-4.4-${{ steps.godot_commit.outputs.hash }}
        restore-keys: |
          godot-build-${{ runner.os }}-4.4-

    - name: Install Godot Build Dependencies
      if: steps.godot-cache.outputs.cache-hit != 'true' || steps.godot-cache-44.outputs.cache-hit != 'true'
      run: |
        pip install scons
        mkdir -p ${{ env.ANGLE_LIB_PATH }}
        curl -L -o ${{ github.workspace }}\angle-lib.zip https://github.com/godotengine/godot-angle-static/releases/latest/download/godot-angle-static-x86_64-msvc-release.zip
        cd ${{ env.ANGLE_LIB_PATH }}
        unzip ${{ github.workspace }}\angle-lib.zip

    - name: Clone Godot Engine
      if: steps.godot-cache.outputs.cache-hit != 'true'
      uses: actions/checkout@v7
      with:
        repository: godotengine/godot
        path: ${{ env.GODOT_SOURCE_PATH }}
        ref: '4.7'

    - name: Clone Godot Engine 4.4
      if: steps.godot-cache-44.outputs.cache-hit != 'true'
      uses: actions/checkout@v7
      with:
        repository: godotengine/godot
        path: ${{ env.GODOT_44_SOURCE_PATH }}
        ref: '4.4'

    - name: Build Godot 4.4
      if: steps.godot-cache-44.outputs.cache-hit != 'true'
      working-directory: ${{ env.GODOT_44_SOURCE_PATH }}
      run: |
        python "${{ env.GODOT_44_SOURCE_PATH }}\misc\scripts\install_d3d12_sdk_windows.py"
        scons platform=windows arch=x86_64 target=editor module_mono_enabled=yes d3d12=yes angle_libs=${{ env.ANGLE_LIB_PATH }} production=yes debug_symbols=no optimize=size module_text_server_adv_enabled=no module_text_server_fb_enabled=yes module_godot_physics_2d_enabled=no module_godot_physics_3d_enabled=no module_jolt_enabled=no module_basis_universal_enabled=no module_bcdec_enabled=no module_bmp_enabled=no module_camera_enabled=no module_csg_enabled=no module_dds_enabled=no module_enet_enabled=no module_etcpak_enabled=no module_fbx_enabled=no module_gltf_enabled=no module_gridmap_enabled=no module_hdr_enabled=no module_interactive_music_enabled=no module_jsonrpc_enabled=no module_ktx_enabled=no module_mbedtls_enabled=no module_meshoptimizer_enabled=no module_minimp3_enabled=no module_mobile_vr_enabled=no module_msdfgen_enabled=no module_multiplayer_enabled=no module_noise_enabled=no module_navigation_2d_enabled=no module_navigation_3d_enabled=no module_ogg_enabled=no module_openxr_enabled=no module_raycast_enabled=no module_tga_enabled=no module_theora_enabled=no module_tinyexr_enabled=no module_upnp_enabled=no module_vhacd_enabled=no module_vorbis_enabled=no module_webrtc_enabled=no module_websocket_enabled=no module_webxr_enabled=no module_zip_enabled=no
        scons platform=windows arch=x86_64 target=template_release module_mono_enabled=yes d3d12=yes angle_libs=${{ env.ANGLE_LIB_PATH }} disable_3d=yes module_regex_enabled=no module_svg_enabled=no production=yes debug_symbols=no optimize=size module_text_server_adv_enabled=no module_text_server_fb_enabled=yes module_godot_physics_2d_enabled=no module_godot_physics_3d_enabled=no module_jolt_enabled=no disable_physics_2d=yes disable_physics_3d=yes module_basis_universal_enabled=no module_bcdec_enabled=no module_bmp_enabled=no module_camera_enabled=no module_csg_enabled=no module_dds_enabled=no module_enet_enabled=no module_etcpak_enabled=no module_fbx_enabled=no module_gltf_enabled=no module_gridmap_enabled=no module_hdr_enabled=no module_interactive_music_enabled=no module_jsonrpc_enabled=no module_ktx_enabled=no module_mbedtls_enabled=no module_meshoptimizer_enabled=no module_minimp3_enabled=no module_mobile_vr_enabled=no module_msdfgen_enabled=no module_multiplayer_enabled=no module_noise_enabled=no module_navigation_2d_enabled=no module_navigation_3d_enabled=no module_ogg_enabled=no module_openxr_enabled=no module_raycast_enabled=no module_tga_enabled=no module_theora_enabled=no module_tinyexr_enabled=no module_upnp_enabled=no module_vhacd_enabled=no module_vorbis_enabled=no module_webrtc_enabled=no module_websocket_enabled=no module_webxr_enabled=no module_zip_enabled=no

    - name: Generate Mono Glue & Build Assemblies 4.4
      if: steps.godot-cache-44.outputs.cache-hit != 'true'
      working-directory: ${{ env.GODOT_44_SOURCE_PATH }}
      run: |
        ${{ env.GODOT_44_EDITOR_PATH }} --headless --generate-mono-glue modules\mono\glue
        python .\modules\mono\build_scripts\build_assemblies.py --godot-output-dir=.\bin --push-nupkgs-local ${{ env.LOCAL_NUGET_PATH }}

    - name: Build Godot
      if: steps.godot-cache.outputs.cache-hit != 'true'
      working-directory: ${{ env.GODOT_SOURCE_PATH }}
      run: |
        python "${{ env.GODOT_SOURCE_PATH }}\misc\scripts\install_d3d12_sdk_windows.py"
        scons platform=windows arch=x86_64 target=editor module_mono_enabled=yes d3d12=yes angle_libs=${{ env.ANGLE_LIB_PATH }} production=yes debug_symbols=no optimize=size module_text_server_adv_enabled=no module_text_server_fb_enabled=yes module_godot_physics_2d_enabled=no module_godot_physics_3d_enabled=no module_jolt_enabled=no module_basis_universal_enabled=no module_bcdec_enabled=no module_bmp_enabled=no module_camera_enabled=no module_csg_enabled=no module_dds_enabled=no module_enet_enabled=no module_etcpak_enabled=no module_fbx_enabled=no module_gltf_enabled=no module_gridmap_enabled=no module_hdr_enabled=no module_interactive_music_enabled=no module_jsonrpc_enabled=no module_ktx_enabled=no module_mbedtls_enabled=no module_meshoptimizer_enabled=no module_minimp3_enabled=no module_mobile_vr_enabled=no module_msdfgen_enabled=no module_multiplayer_enabled=no module_noise_enabled=no module_navigation_2d_enabled=no module_navigation_3d_enabled=no module_ogg_enabled=no module_openxr_enabled=no module_raycast_enabled=no module_tga_enabled=no module_theora_enabled=no module_tinyexr_enabled=no module_upnp_enabled=no module_vhacd_enabled=no module_vorbis_enabled=no module_webrtc_enabled=no module_websocket_enabled=no module_webxr_enabled=no module_zip_enabled=no
        scons platform=windows arch=x86_64 target=template_release module_mono_enabled=yes d3d12=yes angle_libs=${{ env.ANGLE_LIB_PATH }} disable_3d=yes module_regex_enabled=no module_svg_enabled=no production=yes debug_symbols=no optimize=size module_text_server_adv_enabled=no module_text_server_fb_enabled=yes module_godot_physics_2d_enabled=no module_godot_physics_3d_enabled=no module_jolt_enabled=no disable_physics_2d=yes disable_physics_3d=yes module_basis_universal_enabled=no module_bcdec_enabled=no module_bmp_enabled=no module_camera_enabled=no module_csg_enabled=no module_dds_enabled=no module_enet_enabled=no module_etcpak_enabled=no module_fbx_enabled=no module_gltf_enabled=no module_gridmap_enabled=no module_hdr_enabled=no module_interactive_music_enabled=no module_jsonrpc_enabled=no module_ktx_enabled=no module_mbedtls_enabled=no module_meshoptimizer_enabled=no module_minimp3_enabled=no module_mobile_vr_enabled=no module_msdfgen_enabled=no module_multiplayer_enabled=no module_noise_enabled=no module_navigation_2d_enabled=no module_navigation_3d_enabled=no module_ogg_enabled=no module_openxr_enabled=no module_raycast_enabled=no module_tga_enabled=no module_theora_enabled=no module_tinyexr_enabled=no module_upnp_enabled=no module_vhacd_enabled=no module_vorbis_enabled=no module_webrtc_enabled=no module_websocket_enabled=no module_webxr_enabled=no module_zip_enabled=no

    - name: Generate Mono Glue & Build Assemblies
      if: steps.godot-cache.outputs.cache-hit != 'true'
      working-directory: ${{ env.GODOT_SOURCE_PATH }}
      run: |
        ${{ env.GODOT_EDITOR_PATH }} --headless --generate-mono-glue modules\mono\glue
        python .\modules\mono\build_scripts\build_assemblies.py --godot-output-dir=.\bin --push-nupkgs-local ${{ env.LOCAL_NUGET_PATH }}

    - name: Configure Local NuGet Source
      run: |
        @"
        <?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <packageSources>
            <clear />
            <add key="local-godot" value="${{ env.LOCAL_NUGET_PATH }}" />
            <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
          </packageSources>
          <packageSourceMapping>
            <packageSource key="local-godot">
              <package pattern="Godot.NET.Sdk" />
              <package pattern="Godot.SourceGenerators" />
              <package pattern="GodotSharp" />
              <package pattern="GodotSharpEditor" />
            </packageSource>
            <packageSource key="nuget.org">
              <package pattern="*" />
            </packageSource>
          </packageSourceMapping>
        </configuration>
        "@ | Out-File -FilePath nuget.config -Encoding UTF8

    - name: .NET Restore
      run: dotnet restore
      working-directory: ${{ env.SOURCE_PATH }}

    - name: Build Solution
      run: dotnet build
      working-directory: ${{ env.SOURCE_PATH }}

    - name: Install Custom Export Template
      run: |
        $TEMPLATE_DIR = "$env:APPDATA\Godot\export_templates\4.7.1.rc.mono"
        mkdir $TEMPLATE_DIR
        cp ${{ env.GODOT_SOURCE_PATH }}\bin\godot.windows.template_release.x86_64.mono.exe "$TEMPLATE_DIR\windows_release_x86_64.exe"
        $TEMPLATE_DIR = "$env:APPDATA\Godot\export_templates\4.4.2.rc.mono"
        mkdir $TEMPLATE_DIR
        cp ${{ env.GODOT_44_SOURCE_PATH }}\bin\godot.windows.template_release.x86_64.mono.exe "$TEMPLATE_DIR\windows_release_x86_64.exe"

    - name: Export Project
      run: |
        mkdir ${{ github.workspace }}\build\DeltaruneChinesePatcher_Windows
        ${{ env.GODOT_EDITOR_PATH }} --headless --path ${{ env.SOURCE_PATH }} --export-release "Windows Desktop" "${{ github.workspace }}\build\DeltaruneChinesePatcher_Windows\DELTARUNE Chinese Patcher.exe"

    - name: Change for 4.4
      run: |
        $project = "${{ env.SOURCE_PATH }}\project.godot"
        (Get-Content $project) -replace 'config/features=PackedStringArray\("4\.7"', 'config/features=PackedStringArray("4.4"' | Set-Content $project
        $csproj = "${{ env.SOURCE_PATH }}\DeltaruneChinesePatcher.csproj"
        (Get-Content $csproj) -replace 'Godot.NET.Sdk/4\.7\.1-rc', 'Godot.NET.Sdk/4.4.2-rc' | Set-Content $csproj
        $maincs = "${{ env.SOURCE_PATH }}\Main.cs"
        (Get-Content $maincs) -replace 'TranslationServer\.FindTranslations\(current, true\)\[0\]', 'TranslationServer.GetTranslationObject(current)' | Set-Content $maincs
        (Get-Content $maincs) | Where-Object { $_ -notmatch '^\s*DisplayServer\.WindowSetTaskbarProgress' } | Set-Content $maincs
        dotnet restore
        dotnet build
      working-directory: ${{ env.SOURCE_PATH }}

    - name: Export Project (Outdated)
      run: |
        mkdir ${{ github.workspace }}\build\DeltaruneChinesePatcher_Windows_Outdated
        ${{ env.GODOT_44_EDITOR_PATH }} --headless --path ${{ env.SOURCE_PATH }} --export-release "Windows Desktop" "${{ github.workspace }}\build\DeltaruneChinesePatcher_Windows_Outdated\DELTARUNE Chinese Patcher.exe"

    - name: UPX Compressing
      run: |
        ${{ github.workspace }}\upx\upx-5.2.0-win64\upx.exe "${{ github.workspace }}\build\DeltaruneChinesePatcher_Windows\DELTARUNE Chinese Patcher.exe"
        ${{ github.workspace }}\upx\upx-5.2.0-win64\upx.exe "${{ github.workspace }}\build\DeltaruneChinesePatcher_Windows_Outdated\DELTARUNE Chinese Patcher.exe"

    - name: Process files
      run: |
        mkdir "${{ github.workspace }}\build\DeltaruneChinesePatcher_Windows\externals\7zip"
        mkdir "${{ github.workspace }}\build\DeltaruneChinesePatcher_Windows\externals\xdelta3"
        cp "${{ env.SOURCE_PATH }}\externals\7zip\7z.exe" "${{ github.workspace }}\build\DeltaruneChinesePatcher_Windows\externals\7zip\"
        cp "${{ env.SOURCE_PATH }}\externals\xdelta3\xdelta3.exe" "${{ github.workspace }}\build\DeltaruneChinesePatcher_Windows\externals\xdelta3\"
        mkdir "${{ github.workspace }}\build\DeltaruneChinesePatcher_Windows_Outdated\externals\7zip"
        mkdir "${{ github.workspace }}\build\DeltaruneChinesePatcher_Windows_Outdated\externals\xdelta3"
        cp "${{ env.SOURCE_PATH }}\externals\7zip\7z.exe" "${{ github.workspace }}\build\DeltaruneChinesePatcher_Windows_Outdated\externals\7zip\"
        cp "${{ env.SOURCE_PATH }}\externals\xdelta3\xdelta3.exe" "${{ github.workspace }}\build\DeltaruneChinesePatcher_Windows_Outdated\externals\xdelta3\"

    - name: Archive
      run: |
        cd ${{ github.workspace }}\build
        ${{ github.workspace }}\build\DeltaruneChinesePatcher_Windows\externals\7zip\7z.exe a "DeltaruneChinesePatcher_Windows.7z" "DeltaruneChinesePatcher_Windows\*"
        cd ${{ github.workspace }}\build
        ${{ github.workspace }}\build\DeltaruneChinesePatcher_Windows_Outdated\externals\7zip\7z.exe a "DeltaruneChinesePatcher_Windows_Outdated.7z" "DeltaruneChinesePatcher_Windows_Outdated\*"

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: Windows
        path: ${{ github.workspace }}\build\DeltaruneChinesePatcher_Windows.7z

    - name: Upload Artifact (Outdated)
      uses: actions/upload-artifact@v7
      with:
        name: Windows (Outdated)
        path: ${{ github.workspace }}\build\DeltaruneChinesePatcher_Windows_Outdated.7z